### ISSUE TITLE
"Only one inequality filter per query is supported." when doing a range query

### ISSUE THREAD

**Issue by mole440** [3wks/gae-node-nestjs#1]
eg

`filters: {
        cost: [
          {
            op: '>=',
            value: 20000
          },
          {
            op: '<=',
            value: 35000
          },
        ]
      }
`

**Comment by Myrannas** [comment]
Have made a couple of changes on master that should fix this. Can you give it a go and let me know? I can publish etc after you have given it a spin.

**Comment by mole440** [comment]
Fixed. Thanks!
