### ISSUE TITLE
Disabling CSRF interceptor

### ISSUE THREAD

**Issue by n15g** [3wks/gae-node-nestjs#17]
Hey guys,
I can't seem to find an easy way to disable the CSRF interceptor, as it's configured as part of the GCloudModule.

I need to create some anonymous, stateless API endpoints for machine-to-machine integration.... but no cookies means no CSRF tokens... it also means no CSRF vulnerability as well, so I'd rather just do away with the interceptor entirely... or at least disable it on selected endpoints.

It also took me some digging, as it's not documented anywhere that I could find that CSRF protection was enabled by default...

It would be nice to have this configurable, and possibly off by default, but enabled in the generator to avoid confusion like this for API-only deployments.

**Comment by mlev** [comment]
Yes sorry the doco is a little bit sparse (well mostly nonexistent...). I assume you're initialising the app with `configureExpress` function. Here you can pass some options to disable csrf. e.g. the ServerOptions type is this:

```
interface ServerOptions {
  csp?: object;
  csrf?: {
    ignorePaths?: OneOrMany<string | RegExp>;
    sameSite?: boolean;
    disabled?: boolean;
  };
  session: {
    secret: string;
    projectId?: string;
    apiEndpoint?: string;
    cookie?: CookieOptions;
  };
  sessionTimeoutInMinutes?: number;
  staticAssets?: {
    options?: ServeStaticOptions;
    prefix?: string;
    root: string;
  };
}
```

So for CSRF you can either ignore specific paths or disable completely.

The defaults for CSRF are:

```
{
  ignorePaths = [/^\/(tasks\/|system\/).*/],
  sameSite = true, 
  disabled: false
}
```

So if you override ignorePaths you'll probably want to include `tasks` and `system` paths (if you're using them)

**Comment by n15g** [comment]
That worked a treat... thanks!

I hadn't noticed the bootstrap class, or all the express config therein.

Loving this new stack though... makes a nice change from java + thundr!
